let stadiumDatabase = [
  {
    id: 1,
    name: "Tele2 Arena",
    team: "Hammarby IF",
    city: "Stockholm",
    capacity: 31000,
  },
  {
    id: 2,
    name: "Camp Nou",
    team: "FC Barcelona",
    city: "Barcelona",
    capacity: 98000,
  },
  {
    id: 3,
    name: "Wanda Metropolitano",
    team: "Atlético Madrid",
    city: "Madrid",
    capacity: 72000,
  },
  {
    id: 4,
    name: "La Bombanera",
    team: "Boca Juniors",
    city: "Buenos Aires",
    capacity: 54000,
  },
  {
    id: 5,
    name: "Estadio do Dragao",
    team: "FC Porto",
    city: "Porto",
    capacity: 50000,
  },
  {
    id: 6,
    name: "Stade Vélodrome",
    team: "Olympiqe de Marseille",
    city: "Marseille",
    capacity: 67000,
  },
  {
    id: 7,
    name: "Emirates Stadium",
    team: "Arsenal",
    city: "London",
    capacity: 64000,
  },
  {
    id: 8,
    name: "Iberostar Stadium",
    team: "RCD Mallorca",
    city: "Palma",
    capacity: 23000,
  },
  {
    id: 9,
    name: "Ramón Sánchez Pizjuán",
    team: "Sevilla FC",
    city: "Sevilla",
    capacity: 43000,
  },
  {
    id: 10,
    name: "Mestalla",
    team: "Valencia CF",
    city: "Valencia",
    capacity: 55000,
  },
];
